productName: 视频智能监管系统
companyName: ThinkGem
productVersion: V4.1
copyrightYear: 2018
demoMode: false
server:
  port: 9002
  servlet:
    context-path: /js
  tomcat:
    uri-encoding: UTF-8
jdbc: 
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://218.95.183.32:9006/nxwh01?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: nxwh
  password: "12318#nxwh"
  testSql: SELECT 1
spring:
  application:
    name: jeesite-web
  profiles:    
    active: 9002
  main:
    bannerMode: "off"
logging:
  config: classpath:config/logback-spring.xml
